matrix:
  include:
    - BUILDTYPE: Debug
      COMPILER: clang
    - BUILDTYPE: Release
      COMPILER: gnu

pipeline:
  build:
    image: jbakosi/piac-${COMPILER}
    #pull: true
    commands:
     - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} ${CMAKE_COMPILER_FLAGS} -DTPL_DIR=/piac/external/install/${COMPILER}-x86_64 .. && make -sj$(grep -c processor /proc/cpuinfo)
    when:
      COMPILER: clang
      CMAKE_COMPILER_FLAGS: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
  test:
    image: jbakosi/piac-${COMPILER}
    commands:
      - cd build && ctest -j$(grep -c processor /proc/cpuinfo) --output-on-failure
