services:
  synapse:
    image: jbakosi/piac-synapse
    #pull: true
    when:
      matrix:
        COMPILER: gnu

matrix:
  include:
    - BUILDTYPE: Release
      COMPILER: gnu
    - BUILDTYPE: Debug
      COMPILER: clang

pipeline:
  build:
    image: jbakosi/piac-gnu
    #pull: true
    commands:
     - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DTPL_DIR=/piac/external/install/${COMPILER}-x86_64 .. && make -sj$(grep -c processor /proc/cpuinfo)
    when:
      matrix:
        COMPILER: gnu

  build-clang:
    image: jbakosi/piac-clang
    #pull: true
    commands:
     - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DTPL_DIR=/piac/external/install/${COMPILER}-x86_64 .. && make -sj$(grep -c processor /proc/cpuinfo)
    when:
      matrix:
        COMPILER: clang

  test:
    image: jbakosi/piac-${COMPILER}
    commands:
      - cd build && ctest -j$(grep -c processor /proc/cpuinfo) --output-on-failure
