matrix:
  BUILDTYPE:
    - Debug
    - Release

pipeline:
  build:
    image: jbakosi/piac
    commands:
     - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILDTYPE} -DTPL_DIR=/piac/external/install/gnu-x86_64 .. && make -sj$(grep -c processor /proc/cpuinfo)
  test:
    image: jbakosi/piac
    commands:
      - cd build && ctest -j$(grep -c processor /proc/cpuinfo)
